version: '3.7'

services:
  customer-api:
    container_name: customer-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: customer-api
    environment:
      - PORT=4000
      - REDIS_HOST=customer-api-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=senhasupersecreta
      - SSO_CLIENT_SECRET=453000f7-47a0-4489-bc47-891c742650e2
      - SSO_CLIENT_ID=customers
    expose:
      - '4000'
    links:
      - customer-api-redis
    ports:
      - '4000:4000'
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
    depends_on:
      - customer-api-redis
    command: npm run start:dev
  customer-api-redis:
    container_name: customer-api-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass senhasupersecreta
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local